- .circleci/config.yml
- README.md
- api/schema/v1/openperf.yaml
- doc/dev-guide/building.md
- doc/dev-guide/module-api.md
- doc/dev-guide/module-creation.md
- doc/dev-guide/module-packetio-workers.md
- doc/dev-guide/module-packetio.md
- doc/dev-guide/module-socket.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/167)
> Update URLs due to renaming

- mk/pistache.mk
- src/modules/api/api_init.cpp
- src/modules/api/api_utils.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/165)
> Pistache ipv6

- LICENSE
- NOTICES
Adding the missing copyright information and product name to LICENSE and NOTICES files.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/170)
> Update the LICENSE and NOTICES file 

- README.md
- doc/dev-guide/module-api.md
- doc/dev-guide/module-creation.md
- doc/dev-guide/module-packetio.md
- doc/dev-guide/module-socket.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/168)
> Documentation update

- api/schema/v1/block.yaml
- api/schema/v1/modules/block.yaml
- api/schema/v1/openperf.yaml
Upgraded block.yaml from inception-prime repo pull/5:
- Expanded information about block device
- Fixed some minor issues and correсted endpoints and models descriptions
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/186)
> Block generator REST API

- api/schema/v1/openperf.yaml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/206)
> Fix REST API block generator definitions refs

- api/schema/v1/memory.yaml
- api/schema/v1/modules/memory.yaml
- api/schema/v1/openperf.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/189)
> Memory generator REST API

- api/schema/v1/modules/block.yaml
- api/schema/v1/modules/cpu.yaml
- api/schema/v1/modules/memory.yaml
* Add Location header to "create" endpoints
* Make "start" commands creating new result
* Add generator_id field into result definitions
* Wrap CPU generator statistics array into object
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/212)
> Block, memory, CPU generators api improvements

- src/modules/block/handler.cpp
- tests/aat/spec/block_spec.py
- Add response location tests
- Remove tests duplication
- Fix `/block-generators/:id/start` response location header
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/215)
> Improve block generator aat tests

- src/modules/packet/capture/api.hpp
- src/modules/packet/capture/capture_buffer.hpp
- src/modules/packet/capture/pcap_transfer.cpp
- src/modules/packet/capture/server.cpp
- src/modules/packet/capture/server.hpp
- tests/aat/spec/packet_capture_spec.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/226)
> packet/capture: Fix race condition with delete after pcap transfer

- doc/modules/block.md
* API models description
* Commands flow with curl examples
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/221)
> Block I/O load generation docs

- src/modules/packet/analyzer/api.hpp
- src/modules/packet/analyzer/server.cpp
- src/modules/packet/analyzer/sink.cpp
- src/modules/packet/analyzer/sink.hpp
- src/modules/packet/analyzer/sink_transmogrify.cpp
- src/modules/packet/generator/api.hpp
- src/modules/packet/generator/server.cpp
- src/modules/packet/generator/source.cpp
- src/modules/packet/generator/source.hpp
- src/modules/packet/generator/source_transmogrify.cpp
- src/modules/packet/protocol/script/transmogrify_generator.py
- src/modules/packet/protocol/transmogrify/ipv4.cpp
- src/modules/packet/protocol/transmogrify/tcp.cpp
- src/modules/packetio/drivers/dpdk/port_signature_decoder.cpp
- src/modules/packetio/drivers/dpdk/port_signature_encoder.cpp
- tests/aat/spec/packet_analyzer_spec.py
- tests/aat/spec/packet_generator_spec.py
Various minor fixes for the packet modules:
* fix generator/analyzer result state bug
* workaround array bug in generated swagger code
* don't initialize the pga library on the fast path
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/246)
> Packet fixes

- src/modules/block/file_stack.cpp
- src/modules/block/file_stack.hpp
- src/modules/block/server.cpp
Fixes #249 
Fixes removing busy block file
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/251)
> Fix creating multiple block files for the same path

- src/modules/block/task.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/263)
> Fix block I/O load generation performance

- src/modules/memory/generator.cpp
- src/modules/memory/generator.hpp
- src/modules/memory/memory_stat.hpp
- src/modules/memory/server.cpp
- src/modules/memory/swagger_converters.hpp
- src/modules/memory/task_memory.cpp
- src/modules/memory/task_memory.hpp
- src/modules/memory/task_memory_read.cpp
- src/modules/memory/task_memory_read.hpp
- src/modules/memory/task_memory_write.cpp
- src/modules/memory/task_memory_write.hpp
- tests/unit/modules/memory/test_memory_stat.cpp
- Fix the Memory Generator target values calculation.
- Eliminate stuck of results.
Closes #244
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/260)
> Fix target/result of Memory Generator

- src/modules/packet/analyzer/api.hpp
- src/modules/packet/analyzer/api_transmogrify.cpp
- src/modules/packet/analyzer/handler.cpp
- src/modules/packet/analyzer/server.cpp
- src/modules/packet/analyzer/server.hpp
- src/modules/packet/generator/api.hpp
- src/modules/packet/generator/api_transmogrify.cpp
- src/modules/packet/generator/handler.cpp
- src/modules/packet/generator/server.cpp
- src/modules/packet/generator/server.hpp
- tests/aat/spec/packet_analyzer_spec.py
- tests/aat/spec/packet_generator_spec.py
Implements the REST API bulk operations for packet/{analyzer, generator}
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/268)
> Bulk packet api

- src/modules/packet/analyzer/directory.mk
- src/modules/packet/analyzer/server.cpp
- src/modules/packet/analyzer/sink.cpp
- src/modules/packet/analyzer/sink.hpp
- src/modules/packet/analyzer/sink_transmogrify.cpp
- src/modules/packet/analyzer/utils.cpp
- src/modules/packet/bpf/bpf.cpp
- src/modules/packet/bpf/bpf.hpp
- src/modules/packet/bpf/bpf_build.cpp
- src/modules/packet/capture/server.cpp
- src/modules/packet/capture/sink.cpp
- src/modules/packet/capture/sink.hpp
- tests/aat/spec/packet_back_to_back_spec.py
- tests/unit/modules/packet/bpf/test_bpf.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/273)
> packet/bpf: Added  BPF filter support to Analyzer

- src/modules/packet/capture/api.hpp
- src/modules/packet/capture/api_transmogrify.cpp
- src/modules/packet/capture/handler.cpp
- src/modules/packet/capture/server.cpp
- src/modules/packet/capture/server.hpp
- src/modules/packet/capture/utils.cpp
- tests/aat/spec/packet_capture_spec.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/276)
> packet/capture: Add capture bulk API

- src/modules/packet/capture/handler.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/277)
> packet/capture: Remove debug log message

- api/schema/v1/modules/block.yaml
- doc/modules/block.md
- src/modules/block/api.hpp
- src/modules/block/api_transmogrify.cpp
- src/modules/block/device_stack.cpp
- src/modules/block/device_stack.hpp
- src/modules/block/directory.mk
- src/modules/block/file_stack.cpp
- src/modules/block/file_stack.hpp
- src/modules/block/handler.cpp
- src/modules/block/models/device.cpp
- src/modules/block/models/device.hpp
- src/modules/block/models/file.cpp
- src/modules/block/models/file.hpp
- src/modules/block/server.cpp
- src/modules/block/server.hpp
- src/modules/block/virtual_device.cpp
- src/modules/block/virtual_device.hpp
- src/swagger/v1/model/BlockDevice.cpp
- src/swagger/v1/model/BlockDevice.h
- tests/aat/api/v1/client/models/block_device.py
- tests/aat/api/v1/docs/BlockDevice.md
Fixes #256
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/280)
> Initialization progress for block devices

- contrib/docker/README.md
- doc/dev-guide/building.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/282)
> OpenPerf docker runtime image documentation

- Makefile
Fixes #287 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/292)
> Do not fail docker_clean command if docker is not installed on the system

- src/modules/memory/directory.mk
- src/modules/memory/generator.cpp
- src/modules/memory/generator.hpp
- src/modules/memory/swagger_converters.hpp
- src/modules/memory/task_memory.cpp
- src/modules/memory/task_memory.hpp
- src/modules/memory/task_memory_read.cpp
- src/modules/memory/task_memory_write.cpp
- tests/unit/modules/memory/test_memory_task.cpp
Fixes #259
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/286)
> Optimize memory sequence indexes initialization

- src/modules/memory/api_converters.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/298)
> Fix: add Dynamic Results to Swagger object for memory

- mk/libzmq.mk
- src/framework/core/op_init.c
- src/framework/core/op_log.c
- src/framework/core/op_log.h
- src/framework/message/serialized_message.hpp
- src/modules/block/api.hpp
- src/modules/block/api_transmogrify.cpp
- src/modules/block/handler.cpp
- src/modules/block/server.cpp
- src/modules/cpu/api.hpp
- src/modules/cpu/api_converters.cpp
- src/modules/cpu/api_transmogrify.cpp
- src/modules/cpu/handler.cpp
- src/modules/cpu/server.cpp
- src/modules/memory/api.hpp
- src/modules/memory/api_transmogrify.cpp
- src/modules/memory/handler.cpp
- src/modules/memory/server.cpp
- src/modules/packetio/workers/dpdk/worker_client.cpp
- src/modules/timesync/api.hpp
- src/modules/timesync/api_transmogrify.cpp
- src/modules/timesync/handler.cpp
- src/modules/timesync/server.cpp
- tests/unit/framework/test_logging.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/297)
> Zeromq fixes

- tests/unit/framework/directory.mk
- tests/unit/framework/test_dynamic_results.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/302)
> Add Dynamic Results threshold unit tests

- src/modules/memory/generator.cpp
- src/modules/memory/server.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/300)
> Memory Generator fixes

- src/framework/utils/soa_container.hpp
- src/lib/spirent_pga/api.cpp
- src/lib/spirent_pga/api.h
- src/lib/spirent_pga/common/fill.cpp
- src/lib/spirent_pga/common/fill.h
- src/lib/spirent_pga/functions.cpp
- src/lib/spirent_pga/functions.h
- src/lib/spirent_pga/ispc/directory.mk
- src/lib/spirent_pga/ispc/fill_constant.ispc
- src/lib/spirent_pga/scalar/directory.mk
- src/lib/spirent_pga/scalar/fill_constant.cpp
- src/modules/packet/generator/source.cpp
- src/modules/packet/generator/traffic/sequence.cpp
- src/modules/packet/generator/traffic/sequence.hpp
- src/modules/packet/generator/traffic/signature_config.hpp
- src/modules/packet/generator/traffic_transmogrify.cpp
- src/modules/packetio/drivers/dpdk/directory.mk
- src/modules/packetio/drivers/dpdk/mbuf_signature.hpp
- src/modules/packetio/drivers/dpdk/port/prbs_error_detector.cpp
- src/modules/packetio/drivers/dpdk/port/prbs_error_detector.hpp
- src/modules/packetio/drivers/dpdk/port/signature_payload_filler.cpp
- src/modules/packetio/drivers/dpdk/port/signature_payload_filler.hpp
- src/modules/packetio/generic_source.hpp
- src/modules/packetio/memory/dpdk/packet_buffer.cpp
- src/modules/packetio/packet_buffer.hpp
- src/modules/packetio/workers/dpdk/worker_controller.cpp
- src/modules/packetio/workers/dpdk/worker_controller.hpp
- tests/aat/common/helper/traffic.py
- tests/aat/spec/packet_back_to_back_spec.py
- tests/unit/lib/spirent_pga/test_fills.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/304)
> Add generator signature fills

- src/lib/spirent_pga/ispc/.clang-format
- src/lib/spirent_pga/ispc/decode_signatures.ispc
- src/lib/spirent_pga/ispc/signature_scramble.h
- src/lib/spirent_pga/ispc/unpack_and_sum.ispc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/307)
> Spirent pga tweaks

- api/schema/v1/modules/memory.yaml
- doc/modules/memory.md
- src/modules/memory/api_converters.cpp
- src/swagger/v1/model/MemoryGeneratorStats.cpp
- src/swagger/v1/model/MemoryGeneratorStats.h
- tests/aat/api/v1/client/models/memory_generator_stats.py
- tests/aat/api/v1/docs/MemoryGeneratorStats.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/305)
> Change Memory Generator API for consistency

- src/modules/block/generator_stack.cpp
Fix the the bug, appeared in #303 causing acceptance_test failing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/311)
> Fix statistics erase bug

- Makefile
- tests/aat/Makefile
- tests/aat/common/helper/__init__.py
- tests/aat/common/helper/modules.py
- tests/aat/requirements.txt
- tests/aat/spec/block_spec.py
- tests/aat/spec/cpu_spec.py
- tests/aat/spec/dataplane_spec.py
- tests/aat/spec/interfaces_spec.py
- tests/aat/spec/memory_spec.py
- tests/aat/spec/packet_analyzer_spec.py
- tests/aat/spec/packet_back_to_back_spec.py
- tests/aat/spec/packet_capture_spec.py
- tests/aat/spec/packet_generator_spec.py
- tests/aat/spec/ports_spec.py
- tests/aat/test_tool/application_factory.py
- tests/aat/test_tool/cli.py
- tests/aat/test_tool/example.py
- tests/aat/test_tool/example_group.py
- tests/aat/test_tool/formatters.py
- tests/aat/test_tool/loader.py
- tests/aat/test_tool/reporter.py
- tests/aat/test_tool/runnable.py
- tests/aat/test_tool/runners.py
Fixes #284
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/293)
> Modularize test infrastructure

- tests/aat/common/helper/__init__.py
- tests/aat/common/helper/dynamic.py
- tests/aat/common/matcher/__init__.py
- tests/aat/common/matcher/dynamic.py
- tests/aat/spec/block_spec.py
- tests/aat/spec/cpu_spec.py
- tests/aat/spec/memory_spec.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/320)
> Dynamic AAT tests

- src/modules/block/file_stack.cpp
- tests/aat/spec/block_spec.py
Fixes #314
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/317)
> Deleting Block File from the disk

- src/modules/block/file_stack.cpp
Fixes #312
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/318)
> Fix Openperf fault on block file duplicate

- api/schema/v1/modules/memory.yaml
- src/swagger/v1/model/MemoryGeneratorConfig.cpp
- src/swagger/v1/model/MemoryGeneratorConfig.h
Closes #329
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/332)
> Change buffer size data type to int64

- doc/modules/memory.md
Fix description of `reads_per_sec` and `writes_per_sec` configuration parameters to fit reality.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/331)
> Update Memory documentation

- src/modules/cpu/api_converters.cpp
- src/modules/cpu/api_converters.hpp
- src/modules/cpu/handler.cpp
Add validation of the CPU configuration swagger model.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/336)
> CPU Configuration validation

- src/modules/block/api.hpp
- src/modules/block/api_converters.cpp
- src/modules/block/api_transmogrify.cpp
- src/modules/block/handler.cpp
- src/modules/block/server.cpp
- src/modules/cpu/api.hpp
- src/modules/cpu/api_transmogrify.cpp
- src/modules/cpu/handler.cpp
- src/modules/cpu/server.cpp
- src/modules/memory/api.hpp
- src/modules/memory/api_converters.cpp
- src/modules/memory/api_converters.hpp
- src/modules/memory/api_transmogrify.cpp
- src/modules/memory/handler.cpp
- src/modules/memory/server.cpp
Closes #321
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/334)
> Eliminate data wrapping to a pointer in generators API

- src/framework/core/op_cpuset.h
- src/framework/core/op_thread.h
- src/modules/block/block_generator.cpp
- src/modules/block/block_generator.hpp
- src/modules/cpu/generator.cpp
- src/modules/cpu/generator.hpp
- src/modules/memory/generator.cpp
- src/modules/memory/generator.hpp
- src/modules/packetio/drivers/dpdk/eal.cpp
- src/modules/packetio/init.cpp
- src/modules/packetio/workers/dpdk/worker.cpp
- tests/aat/spec/memory_spec.py
Prevent to change OpenPerf affinity mask by DPDK.
Closes #337
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/338)
> Initialize DPDK in dedicated thread

- src/framework/generator/directory.mk
- src/framework/generator/pid_control.cpp
- src/framework/generator/pid_control.hpp
- src/modules/memory/task_memory.cpp
- src/modules/memory/task_memory.hpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/341)
> PID control for Memory Generator

- src/framework/core/op_thread.h
- src/modules/block/block_options.c
- src/modules/block/directory.mk
- src/modules/block/init.cpp
- src/modules/cpu/cpu_options.c
- src/modules/cpu/directory.mk
- src/modules/cpu/generator.cpp
- src/modules/cpu/init.cpp
- src/modules/memory/directory.mk
- src/modules/memory/init.cpp
- src/modules/memory/memory_options.c
#339
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/345)
> CPU mask option for generators

- src/modules/block/block_generator.cpp
- src/modules/memory/generator.cpp
Fix the error of overflow `operations_target` value.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/350)
> Fix result data overflow

- src/modules/packet/analyzer/api.hpp
- src/modules/packet/analyzer/server.cpp
- src/modules/packet/analyzer/sink.cpp
- src/modules/packet/analyzer/sink_transmogrify.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/364)
> Analyzer result fix

- mk/pistache.mk
- src/modules/api/api_init.cpp
- src/modules/packet/capture/handler.cpp
- src/modules/packet/capture/pcap_transfer.cpp
- src/modules/packet/capture/pcap_transfer.hpp
- src/modules/packet/capture/pistache_utils.cpp
Update pistache to the latest version. This pulls in numerous speed,
stability, and robustness fixes. Update client code in packet capture
due to Pistache API changes. Finally, update build file to include new
compilation objects and build options.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/367)
> update to latest version of pistache

- src/modules/packet/analyzer/handler.cpp
- src/modules/packet/generator/handler.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/370)
> Moar chunking

- src/framework/core/directory.mk
- src/framework/core/op_core.h
- src/framework/core/op_list.hpp
- src/framework/core/op_reference.c
- src/framework/core/op_reference.h
- src/modules/packetio/memory/dpdk/mempool.hpp
- src/modules/packetio/memory/dpdk/primary/mempool.cpp
- src/modules/packetio/memory/dpdk/secondary/mempool.cpp
- src/modules/packetio/workers/dpdk/tx_source.cpp
- src/modules/packetio/workers/dpdk/tx_source.hpp
- src/modules/packetio/workers/dpdk/worker.cpp
- src/modules/packetio/workers/dpdk/worker_controller.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/371)
> Moar scaling

- mk/bootstrap.mk
- mk/cpu.mk
- mk/dpdk.mk
- mk/libpcap.mk
- mk/libzmq.mk
- mk/sljit.mk
- mk/spirent_pga.mk
A few updates to improve build flexibility.  With these changes, users can...
* Build a position independent version (PIE)
* Explicitly target machine architectures, e.g. Atom.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/382)
> Better builds

- src/modules/memory/directory.mk
- src/modules/memory/generator.cpp
- src/modules/memory/server.cpp
Resolve #385
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/390)
> modules/memory: add requested memory size check

- src/modules/block/block_generator.cpp
- src/modules/memory/generator.cpp
- src/modules/memory/task_memory.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/388)
> Fix {bytes,ops}_target calculation for Block and Memory

- src/modules/packetio/drivers/dpdk/driver.tcc
- src/modules/packetio/drivers/dpdk/port_info.cpp
- src/modules/packetio/drivers/dpdk/port_info.hpp
- src/modules/packetio/drivers/dpdk/primary/utils.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/398)
> modules/packetio: fix dpdk virtio configuration error

- src/modules/packet/stack/dpdk/tcpip_input.cpp
- src/modules/packetio/drivers/dpdk/port_info.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/405)
> Two bug fixes

- api/schema/v1/modules/packetio.yaml
- src/modules/packetio/drivers/dpdk/driver.tcc
- src/modules/packetio/drivers/dpdk/physical_port.tcc
- src/modules/packetio/drivers/dpdk/port_info.cpp
- src/modules/packetio/drivers/dpdk/port_info.hpp
- src/modules/packetio/generic_port.hpp
- src/modules/packetio/port_utils.cpp
- src/swagger/v1/model/PortConfig_dpdk.cpp
- src/swagger/v1/model/PortConfig_dpdk.h
- tests/aat/api/v1/client/models/port_config_dpdk.py
- tests/aat/api/v1/docs/PortConfigDpdk.md
- tests/aat/common/matcher/port.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/416)
> Add DPDK device MAC addresses to REST API

- src/framework/utils/soa_container.hpp
- src/lib/spirent_pga/api.cpp
- src/lib/spirent_pga/api.h
- src/lib/spirent_pga/common/checksum.cpp
- src/lib/spirent_pga/common/checksum.h
- src/lib/spirent_pga/common/headers.h
- src/lib/spirent_pga/common/signature.cpp
- src/lib/spirent_pga/common/signature.h
- src/lib/spirent_pga/functions.cpp
- src/lib/spirent_pga/functions.h
- src/lib/spirent_pga/ispc/checksum.ispc
- src/lib/spirent_pga/scalar/checksum.cpp
- src/modules/packet/generator/source.cpp
- src/modules/packetio/drivers/dpdk/directory.mk
- src/modules/packetio/drivers/dpdk/port/checksum_calculator.cpp
- src/modules/packetio/drivers/dpdk/port/checksum_calculator.hpp
- src/modules/packetio/drivers/dpdk/port/filter.hpp
- src/modules/packetio/generic_source.hpp
- src/modules/packetio/workers/dpdk/worker_controller.cpp
- src/modules/packetio/workers/dpdk/worker_controller.hpp
- tests/unit/lib/spirent_pga/test_checksums.cpp
Add a callback to calculate checksums for generated packets when no checksumming hardware is available.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/417)
> Add software checksums

- src/lib/packet/type/ipv4_address.hpp
- src/modules/packet/generator/directory.mk
- src/modules/packet/generator/learning.cpp
- src/modules/packet/generator/learning.hpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/414)
> Add Learning State Machine for IPv4 ARP Learning

- src/modules/cpu/generator.cpp
- src/modules/cpu/generator.hpp
Closes #407.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/421)
> modules/cpu: fix statistics in system mode

- api/schema/v1/modules/cpu.yaml
- src/modules/cpu/api_converters.cpp
- src/modules/cpu/cpu_stat.cpp
- src/modules/cpu/cpu_stat.hpp
- src/modules/cpu/generator.cpp
- src/modules/cpu/task_cpu.cpp
- src/modules/cpu/task_cpu_system.cpp
- src/swagger/v1/model/CpuGeneratorCoreStats.cpp
- src/swagger/v1/model/CpuGeneratorCoreStats.h
- src/swagger/v1/model/CpuGeneratorStats.cpp
- src/swagger/v1/model/CpuGeneratorStats.h
- tests/aat/api/v1/client/models/cpu_generator_core_stats.py
- tests/aat/api/v1/client/models/cpu_generator_stats.py
- tests/aat/api/v1/docs/CpuGeneratorCoreStats.md
- tests/aat/api/v1/docs/CpuGeneratorStats.md
- tests/aat/common/matcher/cpu.py
Closes #406
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/412)
> Add target utilization time field to CPU Generator statistics

- src/modules/packet/analyzer/sink_transmogrify.cpp
- src/modules/packet/generator/traffic/sequence.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/418)
> Null stream

- src/modules/block/pattern_generator.cpp
- src/modules/packet/bpf/bpf.cpp
- src/modules/packet/bpf/bpf_build.cpp
- src/modules/packet/stack/dpdk/offload_utils.cpp
- src/modules/packet/stack/dpdk/tcpip_mbox.cpp
- src/modules/packet/stack/utils.cpp
- src/modules/packetio/drivers/dpdk/port/flow_filter.cpp
- src/modules/packetio/drivers/dpdk/topology_utils.cpp
- src/modules/tvlp/controller.cpp
Moved actual code beyond `assert` and deleted the unused `<cassert>` includes.
Closes #426.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/432)
> Fix asserts

- doc/dev-guide/configuration.md
- doc/modules/network.md
- doc/modules/tvlp.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/437)
> Network module documentation

- src/modules/network/task.cpp
- Fix writing to still connecting socket
- Remove errors counter incrementing in read method, it will be done later on `STATE_ERROR`
Fixes #442 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/444)
> Fix writing to connecting socket in network module client

- src/framework/generator/controller.cpp
- src/framework/generator/controller.hpp
- src/framework/generator/directory.mk
- src/framework/generator/feedback_tracker.cpp
- src/framework/generator/feedback_tracker.hpp
- src/framework/generator/worker.cpp
- src/framework/generator/worker.hpp
Closes #429
Based on #440
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/441)
> Generator Framework synchronized operations

- tests/aat/spec/network_spec.py
Small improvements for Network AAT tests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/446)
> tests/aat: improve Network AAT

- mk/framework_lists.mk
- mk/socket_server.mk
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/447)
> mk: fix typos in makefiles

- src/framework/generator/controller.hpp
- src/framework/generator/feedback_tracker.cpp
- src/framework/generator/feedback_tracker.hpp
- src/modules/network/firehose/protocol.hpp
- src/modules/network/firehose/server_tcp.cpp
- src/modules/packet/capture/sink.cpp
- src/modules/packetio/port_handler.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/448)
> Fix tvlp hang due to issues in network load generator

- src/modules/packet/capture/server.cpp
- src/modules/packet/capture/sink.cpp
- src/modules/packet/capture/sink.hpp
- src/modules/packet/capture/sink_transmogrify.cpp
- src/modules/packetio/drivers/dpdk/port/net_ring_fixup.cpp
- src/modules/packetio/drivers/dpdk/port_info.cpp
- src/modules/packetio/drivers/dpdk/port_info.hpp
- src/modules/packetio/workers/dpdk/worker_controller.cpp
- tests/aat/common/matcher/packet_capture.py
- tests/aat/spec/packet_capture_spec.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/452)
> Fix virtio tcp/udp

- src/modules/network/drivers/dpdk.hpp
- src/modules/network/generator.cpp
- src/modules/network/models/generator.hpp
- src/modules/network/models/server.hpp
- src/modules/network/task.cpp
No functional changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/455)
> modules/network: build fixes for clang-10

- tests/scripts/generator_scaling.py
This script uses the REST API to perform bulk configuration and control
of traffic generators for benchmark or testing purposes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/454)
> tests/scripts: add generator scale test script

- api/schema/v1/modules/packet/generator.yaml
Add test signature sequence number behavior to packet generator
documentation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/462)
> api: update packet generator doc

- src/modules/socket/client/api_client.cpp
- src/modules/socket/client/api_client.hpp
- src/modules/socket/client/channels_hashtab.hpp
- src/modules/socket/client/dgram_channel.cpp
- src/modules/socket/client/dgram_channel.hpp
- src/modules/socket/client/io_channel_wrapper.cpp
- src/modules/socket/client/io_channel_wrapper.hpp
- src/modules/socket/client/stream_channel.cpp
- src/modules/socket/client/stream_channel.hpp
- src/modules/socket/server/dgram_channel.cpp
- src/modules/socket/server/socket_factory_linux.cpp
- src/modules/socket/server/socket_utils.cpp
- src/modules/socket/server/stream_channel.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/459)
> Fix socket client channel/eventfd leak

- src/modules/packet/stack/lwip/include/lwipopts.h
- src/modules/socket/server/dgram_channel.cpp
- src/modules/socket/server/dgram_channel.hpp
- src/modules/socket/server/raw_socket.cpp
- src/modules/socket/server/udp_socket.cpp
More lwip/socket fixes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/466)
> Socket fixes

- Makefile
- api/schema/v1/modules/packet/analyzer.yaml
- tests/aat/api/v1/client/api/packet_generators_api.py
- tests/aat/api/v1/docs/PacketGeneratorsApi.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/471)
> Fix issue #469 and #470

- src/modules/tvlp/handler.cpp
TVLP results was hanging when run for a long time due to too large
response.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/473)
> modules/tvlp: send large responses with chunk mode

- src/modules/packet/stack/dpdk/gso_utils.cpp
- src/modules/packetio/memory/dpdk/secondary/mempool.cpp
- src/modules/socket/client/stream_channel.cpp
- src/modules/socket/server/tcp_socket.cpp
stack/socket issues found when testing network module on virtio
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/476)
> Stack fixes

- src/framework/core/op_thread.h
- src/lib/packet/type/endian.hpp
- src/modules/block/pattern_generator.cpp
- src/modules/cpu/instruction_set.hpp
- src/modules/network/drivers/kernel.hpp
- src/modules/packet/bpf/bpf_build.cpp
- src/modules/packet/generator/directory.mk
- src/modules/packet/stack/dpdk/sys_mailbox.cpp
- src/modules/packet/stack/dpdk/tcpip_input.cpp
- src/modules/packetio/drivers/dpdk/port/flow_filter.cpp
- src/modules/packetio/workers/dpdk/tx_queue.cpp
- src/modules/socket/server/pcb_utils.cpp
- src/modules/timesync/bintime.hpp
- tests/aat/common/matcher/api.py
Update libzmq and make minor changes to allow clean compiles with clang 11.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/480)
> Build updates

- src/modules/socket/client/api_client.cpp
- src/modules/socket/server/compat/linux/tcp.h
- src/modules/socket/server/dgram_channel.cpp
- src/modules/socket/server/dgram_channel.hpp
- src/modules/socket/server/icmp_socket.cpp
- src/modules/socket/server/raw_socket.cpp
- src/modules/socket/server/raw_socket.hpp
- src/modules/socket/server/stream_channel.cpp
- src/modules/socket/server/stream_channel.hpp
- src/modules/socket/server/tcp_socket.cpp
- src/modules/socket/server/tcp_socket.hpp
- src/modules/socket/server/udp_socket.cpp
- targets/libopenperf-shim/openperf-shim.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/489)
> Fix some openperf socket API issues when using LD_PRELOAD w/ HTTP servers (nginx, h2o)

- src/lib/spirent_pga/ispc/decode_signatures.ispc
Remove an unused variable and mark some functions inline. No functional
change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/509)
> lib/spirent_pga: do some cleanup

- src/framework/core/op_list.c
- src/framework/core/op_list.h
- src/framework/core/op_log.c
- src/modules/cpu/task_cpu.cpp
- src/modules/memory/buffer.cpp
- src/modules/packet/analyzer/sink.cpp
- src/modules/packet/capture/capture_buffer.cpp
- src/modules/packet/capture/sink.cpp
- src/modules/packet/capture/sink.hpp
- src/modules/packet/generator/source.cpp
- src/modules/packet/generator/traffic/packet_template.cpp
- src/modules/packetio/transmit_table.hpp
- src/modules/packetio/transmit_table.tcc
- src/modules/packetio/workers/dpdk/tx_scheduler.cpp
- src/modules/packetio/workers/dpdk/tx_scheduler.hpp
- src/modules/socket/circular_buffer_producer.tcc
- src/modules/socket/server/api_handler.cpp
- src/modules/timesync/server.cpp
- tests/unit/framework/test_list.cpp
Clean up numerous issues found by running the AAT's using a binary built with `-fsanitize=address`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/512)
> Sanitize addresses

- src/modules/packetio/transmit_table.tcc
Oops. Fix bug introduced in 5918c74307a7e1dac961e346034dffcde8847904.
Obviously, hashes of strings won't be ordered the same way the strings
will, so fix the function that searched by the hashed string value.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/513)
> modules/packetio: fix transmit table ordering issue

- src/modules/packet/analyzer/directory.mk
- src/modules/packet/generator/source.cpp
- src/modules/packet/generator/traffic/sequence.cpp
- src/modules/timesync/chrono.hpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/519)
> Benchmark fallout

- tests/scripts/analyzer_scaling.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/520)
> tests/scripts: remove debugging output

- deps/catch/include/catch.hpp
- mk/libzmq.mk
- src/framework/core/op_list.hpp
- src/framework/memory/aligned_allocator.hpp
- src/framework/memory/std_allocator.hpp
- src/lib/packet/type/endian.hpp
- src/modules/block/virtual_device.hpp
- src/modules/cpu/models/generator_result.hpp
- src/modules/network/firehose/server_tcp.hpp
- src/modules/network/models/generator_result.hpp
- src/modules/network/task.hpp
- src/modules/packetio/generic_port.hpp
- src/modules/timesync/clock.hpp
- tests/unit/Makefile
- tests/unit/framework/test_enum_flags.cpp
- tests/unit/framework/test_init_factory.cpp
- tests/unit/lib/regurgitate/test_benchmark.cpp
- tests/unit/modules/cpu/test_ispc_target.cpp
- tests/unit/modules/packet/analyzer/test_flow_headers.cpp
- tests/unit/modules/packet/bpf/test_bpf.cpp
- tests/unit/modules/packet/generator/test_packet_template.cpp
- tests/unit/modules/packet/generator/test_sequence.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/533)
> Build fixes

- tests/aat/spec/dataplane_spec.py
Update the dataplane AAT to use a random server port instead of a fixed
one. Occasionally, on fast machines, packets from the UDP client->server
test could remain "in flight" during the transition to the
server->client test. This causes the newly instantiated `nc` server
to receive packets from the old client, and hence send packets to
the old client's address.  Since the newly instantiated client
doesn't receive any packets, this triggers an erroneous fail.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/535)
> tests/aat: fix itermittent dataplane issue

- mk/lwip.mk
- src/modules/packet/stack/lwip/include/lwipopts.h
- src/modules/packet/stack/lwip/tcp_in.c
- src/modules/packet/stack/lwip/tcp_out.c
Update lwip to STABLE-2.1.3.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/536)
> deps: update lwip

- src/lib/spirent_pga/scalar/checksum.cpp
Improve checksum performance when generating scalar checksums. This
provides a significant boost when generating 64 byte UDP packets with
signatures, which requires software checksumming.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/541)
> lib/spirent_pga: checksum optimizations

- mk/expected.mk
- mk/yaml_cpp.mk
expected: 1.0.0
immer: v0.7.0
libpcap: 1.10.1
range-v3: 0.11.0
yaml-cpp: 0.7.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/545)
> deps: update depenencies

- deps/patch/dpdk/gro.diff
- mk/dpdk.mk
- src/modules/packet/stack/dpdk/gso_utils.cpp
- src/modules/packet/stack/lwip/gso_utils.h
- src/modules/packetio/workers/dpdk/worker.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/544)
> TCP GRO fix

- .circleci/config.yml
- mk/mode/testing.mk
- src/framework/core/op_version.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/549)
> Minor updates

- mk/pistache.mk
- src/modules/api/api_internal_client.cpp
- src/modules/packet/analyzer/handler.cpp
- src/modules/packet/capture/handler.cpp
- src/modules/packet/generator/handler.cpp
- src/modules/packet/stack/handler.cpp
- src/modules/packetio/port_handler.cpp
Bump pistache to latest version. Update client code. No functional
changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/550)
> deps: update pistache

- tests/unit/modules/packet/capture/test_capture_buffer.cpp
The unit test was using the system clock to generate a starting
timestamp in the fill_capture_buffer_ipv4() function.
The test can fail if the system clock does not increment fast
enough so that the fill_capture_buffer_ipv4() generates
incrementing timestamps.
Test failures were observed when running on WSL2/Hyper-V.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/554)
> tests/unit: fix capture buffer tests when clock update is slow

- mk/dpdk.mk
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Spirent/openperf/561)
> dpdk: add net drivers ena, iavf, netvsc

- src/modules/packet/stack/lwip/nd6.c
Change the precendence of the configured IPv6 gateway address so it has higher precedence than routers found through discovery.
This provides more flexibility because not configuring the gateway address provides the original behavior so functionality can be turned on/off.  The other way it depends if there is a IPv6 router on the network or not.
lwip also currently does not check the prefixes the router is advertising so it is safer to use a configured default route if one is provided.
lwip did not have IPv6 gateway support to begin with, so this change is fixing code I previously added...
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Spirent/openperf/564)
> packet/stack: change IPv6 gateway route precedence

- src/modules/packet/analyzer/handler.cpp
- src/modules/packet/capture/handler.cpp
- src/modules/packet/generator/handler.cpp
- src/modules/packet/stack/handler.cpp
This change fixes an issue where sending a request to the analyzer, capture, generator or stack REST endpoints when packetio is disabled causes the API to hang.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Spirent/openperf/567)
> modules/packetio: API hang when packetio is disabled

- src/modules/packetio/drivers/dpdk/ethdev/af_packet/rte_eth_af_packet.c
fix af packet jumbo frame issue when receiving packets larger than the mbuf size.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Spirent/openperf/571)
> modules/packetio: fix af packet driver SIGSEGV

- src/framework/core/directory.mk
- src/framework/core/op_common.h
- src/framework/core/op_crash_handler.c
- src/modules/block/server.cpp
- targets/openperf/main.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Spirent/openperf/572)
> Crash handler

- src/modules/block/block_generator.cpp
- src/modules/block/block_generator.hpp
- src/modules/block/task.cpp
- src/modules/block/task.hpp
- faster stop when IO is slow
- fix rate thresholds
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Spirent/openperf/573)
> Block IO fixes
