targets/spiperf/doc/spiperf.1.md

This is a first draft and will be updated.
man page "source" is in markdown format designed to be used
with `pandoc`'s man page writer.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/169)

Add spiperf man page

---

api/schema/v1/openperf.yaml
src/swagger/v1/model/TimeKeeperState.cpp
src/swagger/v1/model/TimeKeeperState.h
tests/aat/api/v1/client/models/time_keeper_state.py
tests/aat/api/v1/docs/TimeKeeperState.md

"required" parameter was listed by type instead of by name.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/180)

Fix minor typo in TimeKeeperState swagger spec

---

mk/versions.mk

Swagger requires RFC-3339/ISO-8601 format for
date-time values. Prior to this change the /modules
endpoint was returning build timestamps that were not
fully Swagger compliant.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/183)

Change makefile to generate ISO-8601 build timestamps

---

Dockerfile

The Intel SPMD Program Compiler (ISPC) compiles C-like code into
vectorized kernels. Future commits will use this compiler for code
generaiton.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/188)

Add ISPC to Dockerfile

---

api/schema/v1/cpu.yaml
api/schema/v1/modules/cpu.yaml
api/schema/v1/openperf.yaml

Example for current implementation of CPU generator configuration:
```
{
"id": "0",
"config": [
{
"utilization": 100,
"targets": [
{
"instruction_set": "scalar",
"data_size": 32,
"operation": "int",
"weight": 2
},
{
"instruction_set": "scalar",
"data_size": 64,
"operation": "int",
"weight": 1
}
]
},
{
"utilization": 50,
"targets": [
{
"instruction_set": "AES",
"data_size": 256,
"operation": "encrypt",
"weight": 1
}
]
}
],
"running": true
}
```
Example for current implementation of CPU generator statistics:
```
{
"id": "0",
"active": true,
"timestamp": "2020-02-27T06:16:07.879Z",
"stats": {
"cores": [
{
"available": 123456,
"utilization": 123456,
"system": 123456,
"user": 123456,
"steal": 123456,
"error": 123456,
"targets": [
{
"cycles": 1000,
"latency_min": 123456,
"latency_max": 123456 …
```

CPU generator REST API

---

src/modules/block/block_generator.cpp
src/modules/block/device_stack.cpp
src/modules/block/file_stack.cpp
src/modules/block/file_stack.hpp
src/modules/block/virtual_device.cpp
src/modules/block/virtual_device.hpp

- Fixed fault on deleting device while initialization process
- Fixed using device in wrong state
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/214)

Fix block device faults

---

src/modules/block/file_stack.cpp

mode parameter is required when O_CREAT flag is used
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/216)

block: Fix intermittent file permission errors

---

Dockerfile

ISPC binaries can now be directly downloaded from github, so do so.
Also, bump the version while here.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/220)

Update ISPC verison and link in Dockerfile

---

.circleci/config.yml
.circleci/run_clang_tidy.sh
Makefile

This drops it from ~40 minutes to ~8 minutes.
Though... the static analysis check is *highly* variable.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/224)

Speed up circleci builds

---

src/modules/api/api_config_file_resources.cpp
src/modules/api/api_init.cpp
src/modules/api/api_utils.cpp
src/modules/api/api_utils.hpp

When started with a configuration file, the API startup function
attempts to populate the REST API with the contents of the file.
Previously, this was done in the main thread, which caused a
potential ordering issue when the API module was started before a
module it needed to configure. Fix the issue by spawning a separate
configuration thread to do the configuration so that other modules
aren't blocked during startup.
Also, verify that resource paths are ready before attempting to use
them. This avoids a race between the API config thread and other
modules.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/236)

modules/api: don't block startup

---

src/modules/block/device_stack.cpp
src/modules/block/device_stack.hpp

On startup, the block module attempts to query various devices for block
load testing. If the user lacks permission to access a block device,
then just skip the device instead of logging an error.  Also, only log
block device size errors once. There's no need to repeat the same error
twice.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/227)

modules/block: improve startup logging

---

api/schema/v1/modules/packet/analyzer.yaml
src/swagger/v1/model/PacketAnalyzerFlowCounters.h
src/swagger/v1/model/PacketAnalyzerResult.cpp
src/swagger/v1/model/PacketAnalyzerResult.h
tests/aat/api/v1/client/models/packet_analyzer_flow_counters.py
tests/aat/api/v1/client/models/packet_analyzer_result.py
tests/aat/api/v1/docs/PacketAnalyzerFlowCounters.md
tests/aat/api/v1/docs/PacketAnalyzerResult.md

* If Flows is set to required it can break some JSON decoders when
no flows exist.
* With the property set to required, JSON decoders assume the
property will be specified and non-null. In this case when an
empty array is passed, the JSON encoder encodes that to NULL
rather than an empty array.
(resubmitting to avoid messy merge with previous commit.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/241)

Update AnalyzerResult resource to not require any existing flows

---

src/lib/packet/type/endian.hpp
tests/unit/lib/packet/test_ipv6_address.cpp

This was causing a SIGSEGV with IPv6 addresses due to usage
of movaps instruction on memory not aligned on 16 byte address.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/243)

lib/packet: Fix endian load from unaligned memory

---

Dockerfile

bison and flex are required to compile libpcap
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/267)

Added bison and flex to Dockerfile

---

api/schema/v1/modules/packet/analyzer.yaml
api/schema/v1/openperf.yaml
src/modules/packet/analyzer/api.hpp
src/modules/packet/analyzer/api_transmogrify.cpp
src/modules/packet/analyzer/handler.cpp
src/modules/packet/analyzer/server.cpp
src/modules/packet/analyzer/server.hpp
src/modules/packet/analyzer/sink.cpp
src/modules/packet/analyzer/sink.hpp
src/modules/packet/generator/api.hpp
src/modules/packet/generator/api_transmogrify.cpp
src/modules/packet/generator/handler.cpp
src/modules/packet/generator/server.cpp
src/modules/packet/generator/server.hpp
src/modules/packet/generator/source.cpp
src/modules/packet/generator/source.hpp
src/modules/packetio/generic_workers.hpp
src/modules/packetio/internal_api.hpp
src/modules/packetio/internal_client.cpp
src/modules/packetio/internal_client.hpp
src/modules/packetio/internal_server.cpp
src/modules/packetio/internal_transmogrify.cpp
src/modules/packetio/workers/dpdk/tx_scheduler.cpp
src/modules/packetio/workers/dpdk/worker_controller.cpp
src/modules/packetio/workers/dpdk/worker_controller.hpp
tests/aat/api/v1/client/api/packet_analyzers_api.py
tests/aat/api/v1/docs/PacketAnalyzersApi.md
tests/aat/spec/packet_analyzer_spec.py
tests/aat/spec/packet_back_to_back_spec.py
tests/aat/spec/packet_generator_spec.py

Add some neat tricks:
1. Allow analyzer "resets" - Replace an analyzer result with a new one so that clients can "reset" their analyzer counters.
2. Allow generator "swapping" - Replace a running generator with an idle one to simulate a generator reconfiguration. The swapping operation extracts the number of signature frames generated by the outgoing generator and adds them to the new generator so that there are no gaps or resets in the signature sequence.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/265)

Feature toggles

---

mk/libpcap.mk

Use the actual library file as the rule target to prevent unnecesarily
running the build rule. Also, add explcit configure options to prevent
the build from attempting to link in any dependent libraries that might
be present in the build environment.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/271)

mk: update libpcap makefile

---

targets/libopenperf-shim/openperf-shim.cpp

Make the trace output prettier by removing extraneous commas and
printing the trailing parenthesis before waiting fro the return value.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/275)

targets/libopenperf-shim: improve trace logging

---

mk/libpcap.mk

openperf only uses libpcap for bpf string parsing so it
doesn't need support for netlink.
the netlink library dependency was causing issues with
cross compile using a different sysroot.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/306)

deps/libpcap: Don't link with netlink library

---

src/modules/cpu/cpu_stat.cpp
src/modules/cpu/cpu_stat.hpp
src/modules/cpu/generator.cpp

Add support of the `cores[N].targets[N].operations` field for the CPU dynamic result.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/315)

Add CPU Dynamic target.operations support

---

src/modules/api/api_init.cpp

Increase HTTP Response and Request size up to 1Mb for large queries.
Needed for large generators configurations and particular for TVLP profiles.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/322)

Increase Http Response/Request size up to 1Mb

---

tests/aat/spec/block_spec.py

AAT tests fails with errors like this:
```
Failure/Error: spec/block_spec.py wait_for_file_initialization_done(self.api, file.id, 1)
NameError: name 'time' is not defined
File "spec/block_spec.py", line 74, in wait_for_file_initialization_done
time.sleep(.1)
File "spec/block_spec.py", line 283, in before_each
wait_for_file_initialization_done(self.api, file.id, 1)
``` 
Fix AAT tests block specification by importing the `time` module.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/328)

Fix AAT Block error: name "time" is not defined

---

src/modules/block/handler.cpp
tests/aat/spec/block_spec.py

Change `Location` header in REST replies from absolute to relative path.
For consistency with other modules (particularly CPU and Memory).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/330)

Replace absolute location headers to relative for Block

---

src/framework/core/op_cpuset.c
src/framework/core/op_cpuset.h
src/modules/cpu/cpu.hpp
src/modules/cpu/cpu_linux.cpp
src/modules/cpu/generator.cpp
src/modules/cpu/server.cpp

Fixes #333 
Cpu generator is trying to assing workers thread to cored by sequential number. But kubernetes can assign random cores to the pod. So we have to find available cores to use by CPU generator.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/335)

Assign only available cores to cpu generator workers

---

api/schema/v1/modules/cpu.yaml
src/modules/cpu/api_converters.cpp
src/swagger/v1/model/CpuGeneratorConfig.cpp
src/swagger/v1/model/CpuGeneratorConfig.h
tests/aat/api/v1/client/models/cpu_generator_config.py
tests/aat/api/v1/docs/CpuGeneratorConfig.md

Fixes the indent of `require` property in CPU Generator API specification to pass the Swagger API checks.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/356)

modules/cpu: Fix requirement for "method" property

---

src/modules/api/api_utils.cpp
src/modules/api/api_utils.hpp
src/modules/packet/analyzer/handler.cpp
src/modules/packet/capture/handler.cpp
src/modules/packet/generator/handler.cpp
src/modules/packet/stack/handler.cpp

This fixes observed issues in the generator/analyzer/capture handlers where large replies will block indefinitely due to insufficient buffer space in the Pistache code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/365)

Fix large replies

---

contrib/docker/Dockerfile
contrib/docker/build.sh
contrib/docker/config.yaml
contrib/docker/init.sh

Add an initialization script with processing configuration of the OpenPerf from environment variables beginning with OP_ prefix. Excess configuration was removed from the default configuration file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/373)

contrib/docker: Add init script

---

doc/dev-guide/configuration.md
src/modules/packet/analyzer/init.cpp
src/modules/packet/capture/init.cpp
src/modules/packet/generator/init.cpp
src/modules/packet/stack/dpdk/sys_arch.cpp
src/modules/packet/stack/init.cpp
src/modules/packet/stack/init.hpp
src/modules/packet/stack/lwip/include/arch/sys_arch.h
src/modules/packetio/drivers/dpdk/arg_parser.cpp
src/modules/packetio/drivers/dpdk/arg_parser.hpp
src/modules/packetio/drivers/dpdk/arg_parser_register.c
src/modules/packetio/drivers/dpdk/driver.hpp
src/modules/packetio/drivers/dpdk/driver.tcc
src/modules/packetio/drivers/dpdk/dummy_driver.hpp
src/modules/packetio/drivers/dpdk/primary/driver_factory.cpp
src/modules/packetio/drivers/dpdk/primary/eal_process.cpp
src/modules/packetio/drivers/dpdk/secondary/driver_factory.cpp
src/modules/packetio/drivers/dpdk/topology_utils.cpp
src/modules/packetio/drivers/dpdk/topology_utils.hpp
src/modules/packetio/generic_driver.hpp
src/modules/packetio/init.cpp
src/modules/packetio/init.hpp
src/modules/packetio/workers/dpdk/worker_controller.cpp
src/modules/socket/server/init.cpp
tests/aat/spec/config.yaml
tests/aat/spec/packetio_args_spec.py

Update the packetio initialization code to bail out of the
initialization process if the driver is unusable or the user explicitly
disables it. Add a function so that clients can determine whether the
packetio module is enabled or not. Finally, update dependent modules to
check the packetio module state so they can skip their own
initializations, if necessary.
Also, add some AAT's to verify command line argument processing and
module disablement.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/374)

modules/packetio: add ability to skip packetio init

---

contrib/docker/init.sh

Some long options of the OpenPerf contain the hyphen symbol (-). 
Hyphen is not allowed in the environment variable names.
This fix adds replacement double underscore `__` to hyphen `-` for the vars.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/377)

contrib/docker: Add __ => - replacement for ENV vars

---

api/schema/v1/modules/block.yaml
api/schema/v1/modules/cpu.yaml
api/schema/v1/modules/memory.yaml

Add dynamic_results parameter to each module api specification.
This fix allows to validate OpenAPI 2.0 syntax using the
swagger-cli tool, without getting an error, caused by
incorrect path to the dynamic.yaml file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/378)

api: Fix dynamic_results parameter reference

---

src/modules/socket/server/dgram_channel.cpp
src/modules/socket/server/stream_channel.cpp

Apply the `maybe_unused` tag to variables only used in `assert()`
statements to fix unused variable errors in the release build.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/386)

modules/socket: fix release build

---

src/framework/message/serialized_message.hpp
src/modules/tvlp/api.hpp
src/modules/tvlp/api_transmogrify.cpp
src/modules/tvlp/handler.cpp
src/modules/tvlp/server.cpp

Add triviality check to `serialized_message::push` template to avoid pushing complex objects.
Improve the internal API readability and intelligibility.
Remove excess wrapping messages data to `std::unique_ptr`.
Move needed wrappings to the `api_transmogrify.cpp` file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/384)

TVLP internal API refactoring

---

src/modules/packetio/generic_workers.hpp
src/modules/packetio/internal_api.hpp
src/modules/packetio/internal_client.cpp
src/modules/packetio/internal_client.hpp
src/modules/packetio/internal_server.cpp
src/modules/packetio/internal_transmogrify.cpp
src/modules/packetio/workers/dpdk/worker_controller.cpp
src/modules/packetio/workers/dpdk/worker_controller.hpp

* packetio clients can query for interfaces by interface ID.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/387)

Add interface lookup to packetio internal api

---

api/schema/v1/modules/block.yaml
src/modules/block/api_converters.cpp
src/swagger/converters/block.cpp
src/swagger/v1/model/BlockFile.cpp
src/swagger/v1/model/BlockFile.h
tests/aat/api/v1/client/models/block_file.py
tests/aat/api/v1/docs/BlockFile.md
tests/aat/common/helper/block.py
tests/aat/common/matcher/block.py

Rename `file_size` BlockFile property to `size` for consistency with BlockDevice.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/389)

api/block: rename file_size to size

---

src/modules/block/device_stack.cpp
src/modules/block/device_stack.hpp

Replace a random generated ID of a block device to a system name of such device.
For example, for `/dev/sda` will be assigned id `sda`.
Closes #381.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/395)

modules/block: change ID of device from UUID to name

---

src/modules/block/task.cpp
src/modules/block/task.hpp
src/modules/timesync/chrono.hpp
src/modules/tvlp/worker.cpp
src/modules/tvlp/worker.hpp
src/modules/tvlp/workers/block.cpp
src/modules/tvlp/workers/block.hpp
src/modules/tvlp/workers/cpu.cpp
src/modules/tvlp/workers/cpu.hpp
src/modules/tvlp/workers/memory.cpp
src/modules/tvlp/workers/memory.hpp
src/modules/tvlp/workers/packet.cpp
src/modules/tvlp/workers/packet.hpp

Use start_time from generator statistics, instead of using `now()` method inside TVLP.
Should increases an accuracy of TVLP profile run time.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/397)

modules/tvlp: use start time from generator

---

src/modules/packetio/drivers/dpdk/primary/arg_parser.hpp
src/modules/packetio/drivers/dpdk/primary/arg_parser_register.c
src/modules/packetio/drivers/dpdk/primary/port_info.cpp

Add modules.packetio.dpdk.no-link-interrupts option to disable link
interrupts.
Link interrupts are enabled by default when supported by the driver, but
unfortunately there are cases where link interrupts do not work.
The uio_pci_generic driver doesn't support interrupts at all.
The igb_uio driver only supports one interrupt but the rx interrupt takes
precedence so link interrupts don't work with the igb_uio driver.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/410)

modules/packetio: add option to disable link interrupts

---

api/schema/v1/modules/dynamic.yaml
src/modules/dynamic/api.hpp
src/modules/dynamic/spool.hpp
src/swagger/v1/model/TDigestCentroid.cpp
src/swagger/v1/model/TDigestCentroid.h
tests/aat/api/v1/client/api/block_generator_api.py
tests/aat/api/v1/client/api/cpu_generator_api.py
tests/aat/api/v1/client/api/memory_generator_api.py
tests/aat/api/v1/docs/BlockGeneratorApi.md
tests/aat/api/v1/docs/CpuGeneratorApi.md
tests/aat/api/v1/docs/MemoryGeneratorApi.md

Change datatype of the Dynamic Results weight from `uint32_t` to `uint64_t`.
Closes #400.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/420)

Change datatype of the Dynamic Results weight

---

src/modules/memory/api_transmogrify.cpp
src/modules/memory/buffer.cpp
src/modules/memory/buffer.hpp
src/modules/memory/directory.mk
src/modules/memory/generator.cpp
src/modules/memory/generator.hpp
src/modules/memory/server.cpp
src/modules/memory/task_memory.cpp
src/modules/memory/task_memory.hpp
src/modules/memory/task_memory_read.cpp
src/modules/memory/task_memory_write.cpp
src/modules/tvlp/workers/memory.cpp
src/modules/tvlp/workers/memory.hpp
tests/unit/modules/memory/directory.mk
tests/unit/modules/memory/test_memory_buffer.cpp

PR improves TVLP Memory Generator running.
Changes allow to allocate memory buffer once at TVLP creation time and using this buffer for all generators in the series of TVLP profile.
Closes #399.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/411)

TVLP Shared Buffer for Memory Generators in profile series

---

src/modules/memory/generator.cpp
src/modules/memory/generator.hpp
src/modules/memory/task_memory.cpp
src/modules/memory/task_memory.hpp
src/modules/memory/task_memory_read.cpp
src/modules/memory/task_memory_write.cpp
tests/unit/modules/memory/test_memory_task.cpp

Replaced `std::future` to `std::shared_future` for index vector initialization.
Removed excess preliminary allocating index vector, thus removed unnecessary memory allocation.
Removed copying one index vector to another index vector.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/430)

modules/memory: improve async buffer initialization

---

doc/modules/tvlp.md
src/modules/tvlp/workers/block.cpp
src/modules/tvlp/workers/memory.cpp
src/modules/tvlp/workers/network.cpp

Delete scaling {read,write}_size configuration values
for Block, Memory and Network generators
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/445)

modules/tvlp: delete scaling read/write size

---

src/modules/packetio/memory/dpdk/mempool.hpp
src/modules/packetio/memory/dpdk/primary/mempool.cpp
src/modules/packetio/memory/dpdk/secondary/mempool.cpp
src/modules/packetio/workers/dpdk/tx_source.cpp

Update the memory pool allocation scheme to support two distinct types
of memory pools: shared and unique. Unique pools are used when we can be
confident that the source is going to overwrite the payload for each
transmitted packet. Unique pools are used when that doesn't happen.
This prevents the case where payload data from previously used packet
buffers appears in packets without any user generated payload.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/457)

modules/packetio: change pool allocation scheme

---

src/modules/packetio/memory/dpdk/primary/mempool.cpp

Oops. DPDK packet pools are constrained to a Mersenne number in size. If
a client requests a power of two size, then the actual size might be 1
less instead of doubling the pool size. As a result, we need to use the
actual size of the resulting pool instead of the requested size when
looking for compatible memory pools to share.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/461)

modules/packetio: fix off by 1 error

---

src/modules/socket/client/api_client.cpp
src/modules/socket/client/api_client.hpp
src/modules/socket/client/channels_hashtab.hpp
targets/libopenperf-shim/openperf-shim.cpp

Since openperf clients may be threaded, the client code needs to handle
calls in a thread safe manner. This changelist fixes threaded client
usage in two ways:
1) Use a single global instance for the client hooks. Thread local
instances can't actually construct themselves due to a catch 22
situation with libc functions.
2) Add a lock (eww) to the RPC socket so that client theads can safely
share it.
Additionally, change the channel hashtab to a client member instead of a
singleton. There's no reason for it to exist outside the client now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/463)

modules/socket: fix threaded client usage

---

src/modules/packet/statistics/api_transmogrify.hpp

Oops.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/465)

packet/statistics: fix typo in template code

---

Makefile

Oops. Output the combined schema as a YAML file instead of JSON.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/472)

Makefile: generate a yaml api spec, not json

---

src/framework/core/op_event_loop_epoll.c

This was causing all threads using op_event_loop to exit
when breaking and continuing with gdb.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/475)

framework: op_event_loop ignore epoll_wait() EINTR

---

api/schema/v1/modules/block.yaml
api/schema/v1/modules/cpu.yaml
api/schema/v1/modules/dynamic.yaml
api/schema/v1/modules/memory.yaml
api/schema/v1/modules/network.yaml
api/schema/v1/openperf.yaml
tests/aat/api/v1/client/api/network_generator_api.py
tests/aat/api/v1/docs/NetworkGeneratorApi.md

Golang client generator chokes with how dynamic field
was defined in a subfile then referenced by the top-level
openperf.yaml schema file.
Note: Golang client generated by go-swagger because swagger-codegen
generates broken Golang code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/478)

Minor API changes to fix issue with Golang Client

---

src/modules/packet/analyzer/statistics/flow/counters.hpp

The frame counter struct incorrectly summed the last timestamp value.
Fix it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/479)

packet/analyzer: fix frame counter addition

---

.circleci/run_build.sh
src/modules/packet/generator/directory.mk

The CircleCI build machines will kill processes if the build exceeds the
container's memory limit. Artificially limit our memory usage by
1) Force packet generator template heavy expansion files to build
sequentially.
2) Use a hard cap on the number of cores used by the CirceCI build
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/481)

circleci: limit memory consumption while building

---

src/modules/packet/generator/directory.mk

Oops!  A file can't depend on itself.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/482)

modules/packet: fix serialization dependency

---

Dockerfile

* Add ARM64 cross compile tools
* Update ISPC to version 1.15
* Create llvm-objcopy alternative
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/483)

Update the dockerfile for ARM64 cross compiles

---

src/lib/spirent_pga/common/crc.h
src/lib/spirent_pga/common/signature.cpp
src/lib/spirent_pga/common/x86_64/crc.h

Our CRC calculation is always over the same data size. Hence, update the
calculation functions to only support that one data size and remove any
unnecessary loads and branches. This makes a small, but observable
performance improvement.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/490)

lib/spirent_pga: optimize CRC calculation

---

api/schema/v1/modules/timesync.yaml
src/swagger/v1/model/TimeKeeperState.cpp
src/swagger/v1/model/TimeKeeperState.h
src/swagger/v1/model/TimeKeeperStats.cpp
src/swagger/v1/model/TimeKeeperStats.h
src/swagger/v1/model/TimeKeeperStats_round_trip_times.cpp
src/swagger/v1/model/TimeKeeperStats_round_trip_times.h
tests/aat/api/v1/client/models/time_keeper_state.py
tests/aat/api/v1/client/models/time_keeper_stats.py
tests/aat/api/v1/client/models/time_keeper_stats_round_trip_times.py
tests/aat/api/v1/docs/TimeKeeperState.md
tests/aat/api/v1/docs/TimeKeeperStats.md
tests/aat/api/v1/docs/TimeKeeperStatsRoundTripTimes.md

The timesync swagger specification had numerous properties
(mis)identified as numbers when they should have been integers. Fix
them and update the generated code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/491)

api: fix int definitions for timesync module

---

src/modules/dynamic/spool.hpp

Current implementation of Dynamic Results has some disadvantages:
1. non-constant period of calculation, because of statistics data arrives after each load algorithm spin and Dynamic Results calculates after each spin.
2. zero values in some cases. As consequence of the first peculiarity and concurrent execution some fields of the statistics may be unchanged, thus delta values can be 0.
To resolve this two problems I add computation of Dynamic Results by statically periods. Now, Dynamic Results will be calculated after period of time is elapsed. Default period time is `1s`.
Resolves #493.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/495)

Add computation Dynamic Results by periods

---

api/schema/v1/modules/timesync.yaml
src/modules/timesync/api.hpp
src/modules/timesync/api_transmogrify.cpp
src/modules/timesync/chrono.cpp
src/modules/timesync/chrono.hpp
src/modules/timesync/clock.cpp
src/modules/timesync/clock.hpp
src/modules/timesync/history.cpp
src/modules/timesync/history.hpp
src/modules/timesync/server.cpp
src/swagger/v1/model/TimeKeeper.cpp
src/swagger/v1/model/TimeKeeper.h
src/swagger/v1/model/TimeKeeperState.h
tests/aat/api/v1/client/models/time_keeper.py
tests/aat/api/v1/client/models/time_keeper_state.py
tests/aat/api/v1/docs/TimeKeeper.md
tests/aat/api/v1/docs/TimeKeeperState.md

Add a new property, `maximum-error` to the time-keeper API object so clients can see how accurate the clock thinks it is.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/496)

Add clock error property

---

src/lib/regurgitate/instruction_set_x86.cpp
src/lib/spirent_pga/instruction_set_x86.cpp
src/modules/cpu/instruction_set_x86.cpp

The `xgetbv` instruction necessary for determining AVX support isn't
available on all processors. Use the OSXSAVE bit as a proxy to determine
if the host CPU supports it or not before attempting to execute it.
Update SSE2/SSE4 detection to not require OSXSAVE, since it could be
unset on platforms with support SSE instructions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/497)

src: fix x86 instruction set detection

---

src/modules/packet/stack/dpdk/net_interface.cpp
targets/source-example/Makefile
targets/source-example/main.cpp

The LwIP netif structure only has a pointer for the interface hostname.
As a result, we need to use a pointer to the actual data and not a
temporary reference when "setting" the hostname.
This change allows the stack to advertise the hostname set by the user
when requesting DHCP addresses.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/498)

packet/stack: fix internal config pointers

---

src/modules/packetio/drivers/dpdk/secondary/driver_factory.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/499)

Minor fix for building as a DPDK secondary process

---

api/schema/v1/modules/timesync.yaml
src/modules/timesync/api.hpp
src/modules/timesync/api_transmogrify.cpp
src/modules/timesync/ntp.hpp
src/modules/timesync/server.cpp
src/modules/timesync/server.hpp
src/swagger/v1/model/TimeSourceStats_ntp.cpp
src/swagger/v1/model/TimeSourceStats_ntp.h
tests/aat/api/v1/client/models/time_source_stats_ntp.py
tests/aat/api/v1/docs/TimeSourceStatsNtp.md

Update the NTP client to respond appropriately to server KISS codes, as
specified in RFC 5905.
Add the current poll period to ntp source stats.
Resolves issue #503.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/504)

modules/timesync: improve NTP client behavior

---

src/modules/packet/analyzer/statistics/utils.cpp
tests/aat/common/matcher/packet_analyzer.py
tests/aat/spec/packet_back_to_back_spec.py

Oops. The digest merge inadvertently removed the header string to enum
mapping required to configure header flow counters from swagger. Hence,
add the missing mapping back.
Additionally, update the AAT tests to actually use the header result so
we can't inadvertently drop it again. Update the matcher to check for
valid headers.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/505)

packet/analyzer: add header key to translation code

---

.circleci/config.yml
.circleci/run_build.sh

Downstream now depends on building OpenPerf as a secondary DPDK process.
Make sure this doesn't break silently.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/502)

Add DPDK secondary process build to CircleCI

---

src/modules/packet/generator/learning.cpp

Remove lwip_strerr() since it's a no-op unless LWIP_DEBUG
is defined.
Replaced with LwIP's internal error code -> errno mapping
and a call to good ol strerror().
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/508)

Minor update to packet generator learning code

---

api/client/golang/models/time_keeper.go
api/client/golang/models/time_source_stats.go
api/schema/v1/modules/timesync.yaml
src/swagger/v1/model/TimeKeeper.h
tests/aat/api/v1/client/models/time_keeper.py
tests/aat/api/v1/docs/TimeKeeper.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/507)

api: clarify error units for time-keeper object

---

mk/arch/x86_64.mk

Update the required x86-64 cpu compiler flags to reflect the current
state of the build. With this change, users can compile code for a
generic x86-64 target with the minimum CPU feature set.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/510)

mk: update minimum x86-64 cpu flags

---

mk/dpdk.mk
mk/dpdk_cpu.sh

DPDK uses a unique set of CPU identifiers.
This change maps "standard" -march values to DPDK's unique values.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/511)

Improve CPU type mapping for DPDK builds

---

src/modules/packet/generator/source_transmogrify.cpp

Oops. When using octets for the load specification units, the code
multiplied by the average frame size instead of dividing. Fix it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/517)

packet/generator: fix octet load calculation

---

src/framework/utils/associative_array.hpp
src/modules/packetio/drivers/dpdk/arg_parser.hpp
src/modules/packetio/drivers/dpdk/directory.mk
src/modules/packetio/drivers/dpdk/driver.hpp
src/modules/packetio/drivers/dpdk/driver.tcc
src/modules/packetio/drivers/dpdk/dummy_driver.hpp
src/modules/packetio/drivers/dpdk/names.hpp
src/modules/packetio/drivers/dpdk/port/net_ring_fixup.cpp
src/modules/packetio/drivers/dpdk/port/packet_type_decoder.cpp
src/modules/packetio/drivers/dpdk/port/rss_hasher.cpp
src/modules/packetio/drivers/dpdk/port_info.cpp
src/modules/packetio/drivers/dpdk/port_info.hpp
src/modules/packetio/drivers/dpdk/primary/arg_parser.cpp
src/modules/packetio/drivers/dpdk/primary/port_info.cpp
src/modules/packetio/drivers/dpdk/primary/utils.cpp
src/modules/packetio/drivers/dpdk/quirks.cpp
src/modules/packetio/drivers/dpdk/quirks.hpp
src/modules/packetio/drivers/dpdk/secondary/arg_parser.cpp
src/modules/packetio/drivers/dpdk/secondary/port_info.cpp
src/modules/packetio/generic_driver.hpp
src/modules/packetio/memory/dpdk/primary/pool_allocator.cpp
src/modules/packetio/workers/dpdk/worker_controller.cpp

Various packetio improvements. The highlights are:
* Don't let the worker control DPDK port start/stop, as some port interrogation functions only work when the port is started and don't generate any errors when they return useless info.
* Add driver quirks so that we can filter and ignore known driver problems.
* prefetch header data before parsing packets in all port callbacks.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/522)

Packetio fixups

---

src/modules/packetio/drivers/dpdk/port_info.cpp

Don't return rx packet lengths below the default buffer size. We use
the max packet length for calculating buffer sizes and don't want to
allocate any rx buffers smaller than this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/523)

packetio: clamp port max_rx_pktlen values

---

src/modules/packet/stack/lwip/packet.cpp

The sll_protocol member of the sockaddr_ll struct should be in network
byte order. Hence, don't change the byte order when setting the value.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/524)

packet/stack: fix sll_protocol endianness

---

api/client/golang/models/packet_generator_flow_counters.go
api/schema/v1/modules/packet/generator.yaml
src/modules/packet/analyzer/handler.cpp
src/modules/packet/generator/source.cpp
src/modules/packet/generator/source.hpp
src/modules/packet/generator/source_transmogrify.cpp
src/modules/packetio/drivers/dpdk/arg_parser.cpp
src/modules/packetio/drivers/dpdk/arg_parser.hpp
src/modules/packetio/drivers/dpdk/arg_parser_register.c
src/modules/packetio/drivers/dpdk/primary/arg_parser.cpp
src/modules/packetio/generic_source.hpp
src/modules/packetio/workers/dpdk/tx_scheduler.cpp
src/modules/packetio/workers/dpdk/tx_source.cpp
src/modules/packetio/workers/dpdk/tx_source.hpp
src/swagger/v1/model/PacketGeneratorFlowCounters.cpp
src/swagger/v1/model/PacketGeneratorFlowCounters.h
tests/aat/api/v1/client/models/packet_generator_flow_counters.py
tests/aat/api/v1/docs/PacketGeneratorFlowCounters.md
tests/aat/spec/config.yaml
tests/aat/spec/packet_generator_drop_spec.py
tests/aat/spec/packet_generator_spec.py

This PR makes two main changes:
1) Use the expected transmit count instead of the actual transmit count to determine when to stop a running packet generator when the user specifies a transmit limit.
2) Add a new packetio command line option, modules.packetio.dpdk.drop-tx-overruns. This option instructs the transmit path to drop packets instead of buffering them when the transmit queue is full.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/526)

Transmit behavior updates

---

src/modules/packetio/workers/dpdk/worker_controller.cpp

Tx queues are not required when stack is not running. Expand queue
descriptor filtering from just filtering when core count <= 2 to include
filtering when there's no stack thread.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/527)

Disable Tx Queues When Not Running Stack Thread

---

Dockerfile

The next version of DPDK requires meson and python elftools for
building, so add those to the Dockerfile.
Additionally, update ISPC to the current version, 1.16.1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/537)

Update the Dockerfile for a pending DPDK update

---

mk/dpdk.mk

Build DPDK with the dlopen option for ibverbs. This minimizes the number
of dynamically linked libraries on the openperf binary.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/546)

mk: change dpdk ibverbs linking

---

pkg/deb/install.mk
pkg/deb/templates/lintian-overrides

* Recent changes changed the binary output directory structure. The makefiles supporting the Debian packaging only worked when processing shared libraries one directory deep. The makefiles did not account for this. The problem occurred for the shared libraries, but this fix has been applied to the plugin processing as well.
* Adjusted the lintian file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/548)

fixed the Debian packaging support

---

src/modules/cpu/cpu_transmogrify.cpp

When aggregated, the available CPU stat reported the total run time
times the number of available cores. Adjust that stat to only report the
total run time. This provides consistency with dynamic results and allows
usage calculations to match intended configuration loads, e.g. one fully
loaded core = 100% load.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/553)

modules/cpu: change aggregate available stat

---

.devcontainer/devcontainer.json
.devcontainer/make_dockerfile.sh
.gitignore
.vscode/launch.json
.vscode/settings.json
.vscode/tasks.json

Add vscode files for development using a devcontainer environment.
This has been tested on WSL2 and on a Linux server using SSH.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/555)

add vscode .devcontainer files

---

src/modules/packetio/directory.mk

This is required because interface BPF support requires pcap.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spirent/openperf/557)

modules/packetio: add libpcap dependency

---

src/framework/core/op_cpuset_wrapper.cpp
src/modules/packet/stack/dpdk/memory.cpp
src/modules/packetio/drivers/dpdk/directory.mk
src/modules/packetio/drivers/dpdk/driver.tcc
src/modules/packetio/drivers/dpdk/topology_utils.cpp
src/modules/packetio/drivers/dpdk/topology_utils.hpp

This change fixes issues when lcores use more than 1 CPU (cpuset).
When an lcore cpuset spans multiple NUMA nodes the lcore is not assigned to a socket ID.  The stack code was using the invalid socket ID from the lcore thread to determine the mempool and was causing a crash.
The stack code was changed to use socket ID 0 when the socket ID is not valid.  Additional code was added to handle cases where the device NUMA affiliation does not match the CPU NUMA node.
The packetio driver init was also made lcore cpuset aware so it removes cpus from the default cpuset based off of the cpuset assigned to the lcore instead of assuming the lcore ID is the CPU ID.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …

modules/packetio: DPDK lcore cpuset support

---

.vscode/tasks.json
src/modules/packetio/drivers/dpdk/directory.mk
src/modules/packetio/drivers/dpdk/ethdev/af_packet/directory.mk
src/modules/packetio/drivers/dpdk/ethdev/af_packet/rte_eth_af_packet.c
src/modules/packetio/drivers/dpdk/ethdev/directory.mk

This change adds an alternative af_packet driver "eth_op_af_packet"
which was modified to better support usage in kubernetes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Spirent/openperf/559)

modules/packetio: add customized af_packet driver

---

src/modules/packet/generator/learning.cpp
src/modules/packet/stack/dpdk/net_interface.cpp
src/modules/packet/stack/dpdk/net_interface.hpp
src/modules/packet/stack/lwip/include/lwipopts.h
src/modules/packet/stack/lwip/nd6.c
src/modules/packet/stack/lwip/nd6_op.h
src/modules/packet/stack/lwip/netifapi_ipv6.c
src/modules/packet/stack/lwip/netifapi_ipv6.h
src/modules/packetio/interface_utils.cpp

This change adds minimal support for lwip IPv6 gateway and prefix length.
The IPv6 gateway and prefix lengths are stored outside of the lwip netif in the network_interface class so that the netif.h header doesn't need to be modified.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Spirent/openperf/560)

packet/stack: add ipv6 gateway and prefix length

---

src/modules/packetio/workers/dpdk/tx_scheduler.cpp
src/modules/packetio/workers/dpdk/worker.cpp

Call rte_eth_tx_prepare() before sending packets with rte_eth_tx_burst().
Not calling this function was causing TCP/UDP checksum errors with the Intel XXV710 NIC using checksum offloads.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Spirent/openperf/562)

modules/packetio: call rte_eth_tx_prepare()

---

.devcontainer/make_dockerfile.sh
src/modules/packet/generator/learning.cpp

Fix IPv6 learning so that it will send neighbor solict requests the entire learning time.
Prior to this change learning woud send 1 packet every second for the 1st 3 seconds
and then wait another 27 seconds doing nothing.
This change restarts the ND probe if the address has not been resolved.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Spirent/openperf/563)

Ipv6 learning fix

---

src/modules/packetio/drivers/dpdk/port_info.cpp
src/modules/packetio/drivers/dpdk/port_info.hpp
src/modules/packetio/drivers/dpdk/primary/utils.cpp

MTU must be configured on some NICs to receive jumbo packets. (e.g. vmxnet3, iaxvf, ...)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Spirent/openperf/565)

modules/packetio: configure DPDK port rx mtu

---

src/modules/packetio/drivers/dpdk/ethdev/af_packet/rte_eth_af_packet.c
src/modules/packetio/drivers/dpdk/port_info.cpp
src/modules/packetio/drivers/dpdk/port_info.hpp
src/modules/packetio/drivers/dpdk/primary/utils.cpp

- add support for larger MTU.  tested up to 9000 MTU
- add option to af_packet driver to not configure the kernel interface It may not be safe to modify the interface in some environments
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Spirent/openperf/566)

modules/packetio: af_packet driver enhancements

---

.gitmodules

Upgrade the DPDK library from 21.11 release to 21.11 stable branch to pull in additional patches.
The library was upgraded to fix issues with the iavf driver intermittently failing to initialize due to detecting interface in reset state.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Spirent/openperf/569)

dpdk: upgrade from 21.11 release to stable branch

---

src/modules/packetio/drivers/dpdk/arg_parser.cpp
src/modules/packetio/drivers/dpdk/arg_parser.hpp
src/modules/packetio/drivers/dpdk/arg_parser_register.c
src/modules/packetio/drivers/dpdk/driver.tcc
src/modules/packetio/init.cpp

add ports-required option which causes openperf to exit if it does not find all ports specified in the configuration.
This option was added to support recovery when running in container environments (kubernetes).  There were cases where the DPDK library fails to intialize a VF interface due to the interface being in a reset state and cases where the PF driver does not respond to admin messages.  This appears to be a transient condition when the system is under load and the VF interface eventually seems to recover.
Previously without this option enabled, openperf will log a warning and startup without the intefaces.  This makes it hard to detect issues and recover from it.
With the ports-required option enabled, openperf will exit if it does not find all of the ports it expects which makes …

modules/packetio: add ports-required option

---

src/framework/core/op_event_loop_epoll.c
src/framework/core/op_event_loop_kqueue.c
src/modules/cpu/generator/coordinator.cpp
src/modules/memory/generator/coordinator.cpp

The cpu/memeory generators intermittently crashed in the load update timeout handler due to accessing a results object previously deleted by stop().
The issue appears to have been caused because the event loop may still dispatch pending events after they have been deleted from the event loop in an event handler because they aren't actually removed until later.
This change fixes the issue by marking the events as deleted so they can be ingored until they can be safely removed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Spirent/openperf/574)

fix event timeout crash

---

.circleci/config.yml
src/modules/memory/generator/buffer.cpp

This change fixes the memory generator read-only mode when mlock() is not supported/allowed.
When mlock() is not supported/allowed, a read-only test does not appear to be accessing RAM because the read rates are much higher than the write rates.  This is likely because memory is not being allocated for the mmap.
This change fixes the issue by touching the mmap memory, which forces it to get allocated.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Spirent/openperf/575)

modules/memory: fix read-only test without mlock
